#!/usr/bin/env python

import os

def datacleanup():
    listoffiles = os.listdir(os.getcwd())
    for file in listoffiles:
        if os.path.isfile(pathname):
            if os.path.getsize(file) == 0:
                print 'Removing zero-length file:', file
                os.remove(file)

if __name__ == "__main__":
    datacleanup()

